os:
    - osx
language: generic
sudo: required

osx_image: xcode9

script:
    - swift build
    - swift build -c release
    - swift test

after_success:
    - bash <(curl -s https://codecov.io/bash)
